In [20]:
import numpy as np
from numpy import linalg as LA
#import scipy
from scipy import linalg as la

In [22]:
cov_matrix =  np.array([1,2,3,4,5,6,7,8,9]).reshape(3,3)
cov_matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
a = la.eig(cov_matrix)

In [24]:
a

(array([ 1.61168440e+01+0.j, -1.11684397e+00+0.j, -1.30367773e-15+0.j]),
 array([[-0.23197069, -0.78583024,  0.40824829],
        [-0.52532209, -0.08675134, -0.81649658],
        [-0.8186735 ,  0.61232756,  0.40824829]]))

In [31]:
la.eig(np.diag(np.array([1,2,3])))

(array([1.+0.j, 2.+0.j, 3.+0.j]), array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]))

In [40]:
d, v = la.eig(np.diag(np.array([1,2,3])))

In [41]:
d

array([1.+0.j, 2.+0.j, 3.+0.j])

In [42]:
v

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [43]:
v*d*la.inv(v)

array([[ 1.+0.j, -0.+0.j, -0.+0.j],
       [ 0.+0.j,  2.+0.j, -0.+0.j],
       [ 0.+0.j,  0.+0.j,  3.+0.j]])

## 1. Matrix Eigenvalues Problem:

If a matrix is multiplied with a vector, it returns with another vector. When this returned vector is scaled vector, scale of the vector is eigenvalue of the matrix and the vector is eigenvector of the matrix.
\begin{equation*}
\ A  x  v  = \lambda x v
\end{equation*}